### ISSUE TITLE
Support 2d surfaces in 3d space

### ISSUE THREAD

**Issue by kayarre** [nschloe/optimesh#18]
is it possible to use the optimization on a 2d object in 3d space? 

I am thinking I have some arbitrarily define circles in space I want mesh and optimize.

**Comment by nschloe** [comment]
Flat surfaces? I might look into this. It'll get more difficult for curved surfaces, one would probably have to provide a projection function or something like that.

**Comment by nschloe** [comment]
Okay, should work now for triangular meshes in any dimension. Flat surfaces are fine, but if you use optimesh on something curved, it'll move the geometry.
