### ISSUE TITLE
cannot install from pip

### ISSUE THREAD

**Issue by encorechow** [nschloe/optimesh#26]
I tried to install optimesh from pip, but it throws out a bunch of errors:

Does anyone knows what's wrong with it? my system is ubuntu16.04.

[log.txt](https://github.com/nschloe/optimesh/files/2396621/log.txt)

**Comment by nschloe** [comment]
This I think was a bug in fastfunc (see https://github.com/nschloe/fastfunc/pull/10). Fixed now.
