### ISSUE TITLE
AttributeError: 'MeshTri' object has no attribute 'triangle_quality'

### ISSUE THREAD

**Issue by Doehnert** [nschloe/optimesh#30]
optimesh 0.4.3, Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC
v.1900 64 bit (AMD64)]

I am getting the following error message:
```
AttributeError: 'MeshTri' object has no attribute 'triangle_quality'
```

**Comment by Doehnert** [comment]
optimesh 0.4.3, Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC
v.1900 64 bit (AMD64)]

I am getting the following error message:

AttributeError: 'MeshTri' object has no attribute 'triangle_quality'

**Comment by nschloe** [comment]
Fixed now.
