### ISSUE TITLE
"No edge has more than 2 cells. Are cells listed twice?" Error. Possibly due to non-manifold mesh?

### ISSUE THREAD

**Issue by Cascades** [nschloe/optimesh#40]
I saw another issue (#27 ) which talked about the problem. I found this problem when running the software with an stl file as input... I suspect that it is due to my mesh being non-manifold. It happened on every method I ran with.

I'd love to attach a sample.. but not entirely sure I can :/ sorry about that... Basically wondering if manifold geometry is required?

Thanks

**Comment by nschloe** [comment]
What do you mean by "non-manifold"? I only know manifolds from topology, and there are no flat 2D regions which aren't manifolds, so it's a bit confusing to me.

**Comment by Cascades** [comment]
Sorry, what you are thinking of is what I'm thinking of, from topology. Is the project only for 2D meshes? I may have misunderstood.

**Comment by nschloe** [comment]
2D triangular meshes, to be precise. It may support tets at some point.

**Comment by krober10nd** [comment]
A mesh certainly can be non-manifold 

https://pages.mtu.edu/~shene/COURSES/cs3621/SLIDES/Mesh.pdf

I actually ran into the same error as the original poster but it's not immediately clear what's incorrect with the mesh or how to fix it.

**Comment by nschloe** [comment]
I'll update the readme to say "manifold".
