### ISSUE TITLE
Creating circles with examples/create-circle.py

### ISSUE THREAD

**Issue by Lemmih** [nschloe/optimesh#57]
If you're having problems optimizing a mesh, remember to

 - [x] specify your optimesh version (`optimesh -v`),
    ```
   # optimesh -v
   optimesh 0.6.3 [Python 3.7.5]
   Copyright (C) 2018-2020 Nico Schlömer <nico.schloemer@gmail.com>
   ```

 - [x] specify what command you were running,
    ```
    # python3 create_circle.py
   Traceback (most recent call last):
     File "create_circle.py", line 134, in <module>
       random()
   TypeError: random() missing 1 required positional argument: 'num_points'
   ```
 - [x] attach the mesh (or even better: a small mesh that reproduces the problem).
   No mesh is produced.

The examples/README.md says 'Create original Delaunay triangulation with create-circle.py' but I don't see any code in `create-circle.py` that writes a mesh to disk.

**Comment by nschloe** [comment]
Can't find the text in the readme and the example file also doesn't throw an error anymore.
