### ISSUE TITLE
Support for VTK polydata?

### ISSUE THREAD

**Issue by cbhushan** [nschloe/optimesh#77]
I am working with VTK surfaces and am looking for ways to re-divide the surface (polydata with only triangles) to get similar-sized cells with minimal change from the original surface. optimesh seems to fit the purpose well but on trying optimesh with my VTK polydata I realized that polydata is not supported (error below).

As [VTK currently does not have such optimization function](https://discourse.vtk.org/t/re-divide-surface-to-get-similar-sized-cell/5621), it would be nice to include support of polydata or some suggestions of how to use optimesh with VTK polydata.

 - [x] specify your optimesh version (`optimesh -v`),
   ```
   $ optimesh -v
   optimesh 0.8.0 [Python 3.6.10]
   Copyright (C) 2018-2020 Nico Schlömer <nico.schloemer@gmail.com>
   ```
 - [x] specify what command you were running
```
$ optimesh sphere_radius_1.vtk sphere_radius_1_cvt-uniform-qnf.vtk -m cvt-full
Traceback (most recent call last):
  File "/localopt/bin/optimesh", line 8, in <module>
    sys.exit(main())
  File "/localopt/lib/python3.6/site-packages/optimesh/cli/main.py", line 150, in main
    mesh = meshio.read(args.input_file)
  File "/localopt/lib/python3.6/site-packages/meshio/_helpers.py", line 69, in read
    return reader_map[file_format](filename)
  File "/localopt/lib/python3.6/site-packages/meshio/vtk/_vtk.py", line 150, in read
    out = read_buffer(f)
  File "/localopt/lib/python3.6/site-packages/meshio/vtk/_vtk.py", line 181, in read_buffer
    _read_section(f, info)
  File "/localopt/lib/python3.6/site-packages/meshio/vtk/_vtk.py", line 207, in _read_section
    "', '".join(vtk_dataset_types), info.dataset["type"]
meshio._exceptions.ReadError: Only VTK 'UNSTRUCTURED_GRID', 'STRUCTURED_POINTS', 'STRUCTURED_GRID', 'RECTILINEAR_GRID' supported (not POLYDATA).
```

 - [x] attach the mesh (or even better: a small mesh that reproduces the problem).
   VTK polydata file: [sphere_radius_1_small.zip](https://github.com/nschloe/optimesh/files/6406930/sphere_radius_1_small.zip). The file was generated by code snippet below:

    ```
    import vtk
    radius = 1
    sph = vtk.vtkSphereSource()
    sph.SetRadius(radius)
    sph.SetPhiResolution(40)
    sph.SetThetaResolution(40)
    sph.LatLongTessellationOff()

    sph.Update()
    poly = sph.GetOutput()

    writer = vtk.vtkPolyDataWriter()
    writer.SetFileTypeToBinary()
    writer.SetInputData(poly)
    writer.SetFileName('sphere_radius_1_small.vtk')
    writer.Write()
    ```

**Comment by nschloe** [comment]
> optimesh seems to fit the purpose well

Probably not. For optimesh to work on surfaces, you need to have a function to that projects points onto your surface. If you just have a VTK file, you probably don't have that.

It would work for spheres though, if that's all your after.

The polydata read bug is a missing feature from meshio, so I'll just point you to https://github.com/nschloe/meshio/issues/527.

**Comment by cbhushan** [comment]
Sphere was just toy example. My actual surfaces are generated as iso-surface from 3D volumetric data (in VTK: Smooth volumetric data → marching cubes → smooth using vtkWindowedSincPolyDataFilter → vtkQuadricDecimation). Although I do not have analytical expression of my volumetric data, I can numerically evaluate the function value at any arbitrary point (under interpolation limits). Would that be good enough for optimesh optimization? 

I have been looking at [surface mesh smoothing example](https://github.com/nschloe/optimesh#surface-mesh-smoothing) in readme, which also uses sphere. Is argument `x` to class functions `f` and `grad` just 3D coordinate in the space? Also is `grad` supposed to return the gradient at point `x` as described below? I think even grad can be computed numerically. 

![image](https://user-images.githubusercontent.com/3436053/116740128-94323500-a9c2-11eb-9e1e-e2385ec5e035.png)

**Comment by nschloe** [comment]
> Would that be good enough for optimesh optimization?

Yeah, I think that should be alright. grad is the gradient just like you describe, too.
