### ISSUE TITLE
constrained boundary mesh

### ISSUE THREAD

**Issue by ksHamburg** [nschloe/optimesh#79]
Does the optimization technique a triangular planar mesh preserve the boundary mesh and/or some specified interior segements, similar to a constrained delaunay triangulation?

**Comment by nschloe** [comment]
The boundaries are preserved, yes. Interior points are free to move, but I could add specifying a subset that's fixed.

**Comment by ksHamburg** [comment]
How can this be done. Could you provide an example? I have triangular meshes with specific interior lines that can not be altered. much like the boundary segement example of shewchuk (https://www.cs.cmu.edu/~quake/triangle.convex.html).
Any advice would be appreciated.

**Comment by nschloe** [comment]
>  Could you provide an example?

Like I said, It's not implemented yet, so I cannot give an example. If you want to have this quickly, you could dive in the code and PR. Otherwise I'll do it in my spare time at some point. I could move this into my working time if anyone sponsors this.

**Comment by ksHamburg** [comment]
Thanks for responding again. I did not got the information out of your comment. I will dive into the code myself and see what can be done.
