### ISSUE TITLE
Import error: cannot import name 'NDArray' from 'numpy.typing'

### ISSUE THREAD

**Issue by Dee718** [nschloe/optimesh#83]
Hi,

I have v0.8.3 installed using pip but I am getting the following import error both on MacOS and on linux:
`
import optimesh`

`ImportError: cannot import name 'NDArray' from 'numpy.typing' (.../anaconda3/envs/fenics_2021/lib/python3.7/site-packages/numpy/typing/__init__.py)`

Do you know how I can fix this? 

Thanks!

**Comment by nschloe** [comment]
Update numpy to 1.20+. Should be in the version requirements, I'll fix that.

**Comment by Dee718** [comment]
Thanks!
